# Generated by Django 3.0.6 on 2020-05-10 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('changedetection', '0003_auto_20200510_1020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='video1',
            field=models.FileField(blank=True, null=True, upload_to='media/video1/'),
        ),
    ]
