# Generated by Django 3.0.6 on 2020-05-10 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('changedetection', '0004_auto_20200510_1025'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='video1',
        ),
        migrations.RemoveField(
            model_name='image',
            name='video2',
        ),
        migrations.AddField(
            model_name='image',
            name='pdf',
            field=models.FileField(null=True, upload_to='media/pdfs/'),
        ),
    ]
