# Generated by Django 3.0.6 on 2020-05-10 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('changedetection', '0005_auto_20200510_1028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='pdf',
            field=models.FileField(blank=True, upload_to='media/pdfs/'),
        ),
    ]
