# Generated by Django 3.0.6 on 2020-05-10 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('changedetection', '0007_auto_20200510_1032'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='video2',
            field=models.FileField(blank=True, upload_to='media/video/'),
        ),
    ]
