# Generated by Django 3.0.6 on 2020-05-10 05:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('changedetection', '0008_image_video2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='cover',
        ),
    ]
