# Generated by Django 3.0.6 on 2020-05-10 05:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('changedetection', '0010_auto_20200510_1041'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='pdf',
            new_name='video1',
        ),
    ]
